Lazy-load virtualenvwrapper

diff --git a/.zsh/python b/.zsh/python
--- a/.zsh/python
+++ b/.zsh/python
@@ -2,19 +2,6 @@
 # Virtualenvwrapper
 #
 
-# Shell hooks; look in all possible locations and for both old and new versions
-# of the script, just in case I find myself on an older system.
-ROOTS=(/usr/bin /usr/local/bin)
-SUFFIXES=(_bashrc .sh)
-for root in $ROOTS; do
-    for suffix in $SUFFIXES; do
-        p=$root/virtualenvwrapper$suffix
-        if [[ -f $p ]]; then
-            virtualenvwrapper=$p
-        fi
-    done
-done
-
 # Don't blow up when PYTHONDONTWRITEBYTECODE is set
 export VIRTUALENV_USE_DISTRIBUTE=1
 # Not sure why the hell the docs say one thing and the code another.
@@ -26,7 +13,54 @@ export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
 
 export WORKON_HOME=~/.virtualenvs
 test -d $WORKON_HOME || mkdir $WORKON_HOME
-[[ -n "$virtualenvwrapper" && -f $virtualenvwrapper ]] && source $virtualenvwrapper
+
+
+#
+# Lazy-loading of virtualenvwrapper itself.  Copied from
+# https://gist.github.com/2483204 which is itself a tweak of
+# http://blog.arongriffis.com/post/dynamic-virtualenvwrapper
+#
+if [[ $(type -w workon) != "workon: function" ]]; then
+  virtualenv_funcs=( workon deactivate mkvirtualenv )
+
+  load_virtualenv() {
+    # If these already exist, then virtualenvwrapper won't override them.
+    unset -f "${virtualenv_funcs[@]}"
+
+    # virtualenvwrapper doesn't load if PYTHONPATH is set, because the
+    # virtualenv python doesn't have the right modules.
+    declare _pp="$PYTHONPATH"
+    unset PYTHONPATH
+
+    # Attempt to load virtualenvwrapper from its many possible sources...
+    _try_source() { [[ -f $1 ]] || return; source "$1"; return 0; }
+    _try_source /usr/local/bin/virtualenvwrapper.sh || \
+    _try_source /etc/bash_completion.d/virtualenvwrapper || \
+    _try_source /usr/bin/virtualenvwrapper.sh
+    return_status=$?
+    unset -f _try_source
+
+    # Restore PYTHONPATH
+    [[ -n $_pp ]] && export PYTHONPATH="$_pp"
+
+    # Did loading work?
+    if [[ $return_status != 0 || $(type -w "$1") != "$1: function" ]]; then
+      echo "Error loading virtualenvwrapper, sorry" >&2
+      return $return_status
+    fi
+
+    # Chain-load the appropriate function
+    "$@"
+  }
+
+  for v in "${virtualenv_funcs[@]}"; do
+    eval "$v() { load_virtualenv $v \"\$@\"; }"
+  done
+fi
+#
+# End of cribbed code
+#
+
 
 # mkvirtualenv_help is irritating re: tab completion, and unnecessary, as
 # mkvirtualenv --help still works fine.
